// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYUo_BdzYNn7vT7kH1w34OuOTZFrhgPTY',
    appId: '1:135503494082:web:9241e7f09bcf22030e345b',
    messagingSenderId: '135503494082',
    projectId: 'motoh-e469f',
    authDomain: 'motoh-e469f.firebaseapp.com',
    storageBucket: 'motoh-e469f.firebasestorage.app',
    measurementId: 'G-Q0W8TWLQWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qu4Rde92OXQqdle2MQ2K1nHguyAybpE',
    appId: '1:135503494082:android:7b62f8fe1a4155030e345b',
    messagingSenderId: '135503494082',
    projectId: 'motoh-e469f',
    storageBucket: 'motoh-e469f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMokfJMIx9_vsdgmxH_WzmTEYc4L5NR0U',
    appId: '1:135503494082:ios:595267183e5f72cb0e345b',
    messagingSenderId: '135503494082',
    projectId: 'motoh-e469f',
    storageBucket: 'motoh-e469f.firebasestorage.app',
    iosBundleId: 'com.motoh.motohClient',
  );
}
